---
name: Publish Artifacts

env:
  JAVA_VERSION: 8

on:
  workflow_dispatch:
  release:
    types: [ released ]

jobs:
  publish-artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CHECKOUT_PAT }}
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{  env.JAVA_VERSION }}
          distribution: 'temurin'
      - name: Set up Gradle
        run: chmod a+x gradlew
      - name: Build
        run: ./gradlew build
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: android/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          # override default build-tools version (33.0.0) -- optional
          BUILD_TOOLS_VERSION: "34.0.0"
      - name: Publish
        run: ./gradlew publish
        env:
          GITHUB_USERNAME: scriptgate
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SIGNED_RELEASE_FILE: 'build/outputs/apk/release/android-release-unsigned-signed.apk'
